# Generated by Django 3.2.8 on 2021-10-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='data_nascimento',
        ),
    ]
